config/routes.rb
Rails.application.routes.draw do

  # scope as "amenities_create" do
  #   post "/amenities/create/amenity" => "amenities#create"
  # end


  post '/update/user/description' => 'users#update_description'

  scope as: "listings_delete" do  
    post "/listings/delete/:id" => "listings#delete"
  end

  scope as: "braintree_new" do
    get '/braintree/new/:id' => 'braintree#new'
    post '/braintree/new/:id' => 'braintree#new'
  end
  
  scope as: "braintree_checkout" do
    post '/braintree/checkout/:id' => "braintree#checkout"
    get '/braintree/checkout/:id' => "braintree#checkout"
  end

  root 'sessions#login'

  get "/auth/:provider/callback" => "sessions#create_from_omniauth"    

  get "/users_edit" => "users#show"
  post "/users_edit" => "users#edit"

  get "/listings_search_box" => "listings#search_box"
  post "/listings_search_box" => "listings#search_box"
  get "/listings_search" => "listing#search"
  post "/listings_search" => "listings#search_results" 

  post "/host_property" => "listings#create"
  get "/host_property" => "listings#create"
  get "/listings_create" => "listings#create"
  post "listings_create" => "listings#create_new_listing"  

  scope as: "listing" do
    get "/listing/:id" => "listings#show"    
  end

  post "/listing/:id" => "listings#update"

  scope as: "user_profile" do
    post "/user_profile/:id" => "users#profile"
    get "/user_profile/:id" => "users#profile"
  end

  scope as: "create_booking" do
    post "/create_booking/:id" => "bookings#create"
    get "/create_booking/:id" => "bookings#create"
  end

  delete "/log_out" => "sessions#destroy", as: :custom_sign_out
  get "/sign_in" => "sessions#sign_in", as: :custom_sign_in 


  resources :users, only: [:create, :edit, :update] do
    resource :password,
    controller: "clearance/passwords",
    only: [:create, :edit, :update]
  end
  
  post "/session" => "sessions#create"


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/braintree_controller.rb
require 'date'
class BraintreeController < ApplicationController
  before_action :require_login 

  def new        
    #only make this page accessable to the current user
    if params[:booking][:user_id].to_i != current_user.id      
      redirect_to listings_search_box_path
    else
      @client_token = Braintree::ClientToken.generate
      num_of_nights =  Date.parse(params[:booking][:end_date]) - Date.parse(params[:booking][:start_date])
      price_per_night = Listing.find(params[:booking][:listing_id]).price_per_night
      total_price = (num_of_nights * price_per_night).to_i
      params[:booking][:total_price] = total_price
      session["booking"] = params[:booking]
      render "payment"
    end

  end

  def checkout    

    payable_amount = session["booking"]["total_price"].to_i

    nonce_from_the_client = params[:checkout_form][:payment_method_nonce]

    result = Braintree::Transaction.sale(
      :amount => payable_amount, 
      :payment_method_nonce => nonce_from_the_client,
      :options => {
        :submit_for_settlement => true
      }
      )

    if result.success?   
      redirect_to create_booking_path(params[:id])
    else
     redirect_to :root, :flash => { :error => "Transaction failed. Please try again." }
   end

 end
end

app/helpers/braintree_helper.rb
module BraintreeHelper
end

app/views/braintree/_payment.html.erb
<div class="payment-frame">

  <%= form.label :card_number, "Credit Card Number", html: {class: "hosted-fields--label"} %>
  <div id="card-number" class="hosted-field"></div>

  <%= form.label :expiration_date, "Expiration Date", html: {class: "hosted-fields--label"} %>
  <div id="expiration-date" class="hosted-field"></div>

  <%= form.label :cvv, "CVV", html: {class: "hosted-fields--label"} %>
  <div id="cvv" class="hosted-field"></div>

  <%= form.hidden_field "payment_method_nonce" %>

  <div class="button-container">
    <%= form.submit "Purchase", disabled: true, class: "btn btn-primary", id: "submit-payment-btn" %>
  </div>
</div>

app/views/braintree/payment.html.erb
<%= form_for :checkout_form, url: braintree_checkout_path(params[:id]), html: { id: "cardForm"} do |form| %>
<%= render partial: '/braintree/payment', locals: {form: form} %>
<%end%>

<!-- Load the Client component. -->
<script src="https://js.braintreegateway.com/web/3.6.3/js/client.min.js"></script>

<!-- Load the Hosted Fields component. -->
<script src="https://js.braintreegateway.com/web/3.6.3/js/hosted-fields.min.js"></script>

<script>
 var form = document.querySelector('#cardForm');
 var submit = document.querySelector('#submit-payment-btn');

 braintree.client.create({
   authorization: '<%= @client_token %>'
 }, function (clientErr, clientInstance) {
   if (clientErr) {
     console.error(clientErr);
     return;
   }

        // This example shows Hosted Fields, but you can also use this
        // client instance to create additional components here, such as
        // PayPal or Data Collector.

        braintree.hostedFields.create({
          client: clientInstance,
          styles: {
            'input': {
              'font-size': '14px'
            },
            'input.invalid': {
              'color': 'red'
            },
            'input.valid': {
              'color': 'green'
            }
          },
          fields: {
           number: {
             selector: '#card-number',
             placeholder: '4111 1111 1111 1111'
           },
           cvv: {
             selector: '#cvv',
             placeholder: '123'
           },
           expirationDate: {
             selector: '#expiration-date',
             placeholder: '10/2019'
           }
         }
       }, function (hostedFieldsErr, hostedFieldsInstance) {
        if (hostedFieldsErr) {
          console.error(hostedFieldsErr);
          return;
        }

        submit.removeAttribute('disabled');

        form.addEventListener('submit', function (event) {
          event.preventDefault();

          hostedFieldsInstance.tokenize(function (tokenizeErr, payload) {
            if (tokenizeErr) {
              console.error(tokenizeErr);
              return;
            }

               // Put `payload.nonce` into the `payment_method_nonce` input, and then
        // submit the form. Alternatively, you could send the nonce to your server
        // with AJAX.
        document.querySelector('input[name="checkout_form[payment_method_nonce]"]').value = payload.nonce;
        form.submit()
      });
        }, false);
      });
      });

    </script>