config/routes.rb
Rails.application.routes.draw do

  # scope as "amenities_create" do
  #   post "/amenities/create/amenity" => "amenities#create"
  # end


  post '/update/user/description' => 'users#update_description'

  scope as: "listings_delete" do  
    post "/listings/delete/:id" => "listings#delete"
  end

  scope as: "braintree_new" do
    get '/braintree/new/:id' => 'braintree#new'
    post '/braintree/new/:id' => 'braintree#new'
  end
  
  scope as: "braintree_checkout" do
    post '/braintree/checkout/:id' => "braintree#checkout"
    get '/braintree/checkout/:id' => "braintree#checkout"
  end

  root 'sessions#login'

  get "/auth/:provider/callback" => "sessions#create_from_omniauth"    

  get "/users_edit" => "users#show"
  post "/users_edit" => "users#edit"

  get "/listings_search_box" => "listings#search_box"
  post "/listings_search_box" => "listings#search_box"
  get "/listings_search" => "listing#search"
  post "/listings_search" => "listings#search_results" 

  post "/host_property" => "listings#create"
  get "/host_property" => "listings#create"
  get "/listings_create" => "listings#create"
  post "listings_create" => "listings#create_new_listing"  

  scope as: "listing" do
    get "/listing/:id" => "listings#show"    
  end

  post "/listing/:id" => "listings#update"

  scope as: "user_profile" do
    post "/user_profile/:id" => "users#profile"
    get "/user_profile/:id" => "users#profile"
  end

  scope as: "create_booking" do
    post "/create_booking/:id" => "bookings#create"
    get "/create_booking/:id" => "bookings#create"
  end

  delete "/log_out" => "sessions#destroy", as: :custom_sign_out
  get "/sign_in" => "sessions#sign_in", as: :custom_sign_in 


  resources :users, only: [:create, :edit, :update] do
    resource :password,
    controller: "clearance/passwords",
    only: [:create, :edit, :update]
  end
  
  post "/session" => "sessions#create"


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/listing.rb
class Listing < ApplicationRecord
   #Db
   belongs_to :user
   has_many :amenities, dependent: :destroy   
   has_many :bookings, dependent: :destroy
   accepts_nested_attributes_for :amenities

   #validators   
   mount_uploader :image, AvatarUploader
   validates :description, presence: true
   validates :country, presence: true
   validates :city, presence: true
   validates :street, presence: true
   validates :price_per_night, presence: true
   validates :number_of_guests, presence: true   
   validates :property_scope, presence: true   
   validates :property_type, presence: true   
   
end

app/controllers/listings_controller.rb
include ListingsHelper

class ListingsController < ApplicationController
   before_action :require_login 
   
   def search_box         
      @display_carousel = true
   end

   def delete
      listing = Listing.find(params[:id])
      listing.destroy
      redirect_to user_profile_path(current_user.id)      
   end

   def update      
      listing = Listing.find(params[:id])
      listing.update(image: params[:listing][:image])
      redirect_to user_profile_path(current_user.id)
   end

   def search      
      render "show_search_results"
   end

   def create
      @display_carousel = true
   end

   def create_new_listing         

      listing = Listing.new(listing_params)
      listing.user_id = current_user.id       
      
      # listing.amenities     
      
      if listing.save
         #listing.amenities.create(params[:amenity])    
         params[:amenity].each do |amenity|
            
            amenity = Amenity.new(listing_id: listing.id, amenity: params[:amenity][amenity])      
            amenity.save
         end         
         current_user.update(:role => 1)
         redirect_to user_profile_path(current_user.id)
      end
   end   

   def listing     
   end

   def show
      @listing = Listing.find(params[:id])
      @amenities = Amenity.where("listing_id = ?", "#{@listing.id}")
      render "listing"
   end

   def search_results             

   #search through city        
   @listings = Listing.where("city LIKE ?", "%#{params[:user][:location]}%")                              
   
   #if nothing is found, search through country
   if @listings[0] == nil
      @listings = Listing.where("country LIKE ?", "%#{params[:user][:location]}%")                        
   end

   #if nothing is sitll found, return the whole table  
   if @listings[0] == nil
      @listings = Listing.all
   end      

   @listings = @listings.paginate(page: params[:page], per_page: 9)
   render "show_search_results"
end

private

def listing_params      
   params.require(:user).permit(:title, :description, :country, :city, :street, :price_per_night, :property_type, :property_scope, :number_of_guests, :image, :amenity)
end   

end

app/helpers/listings_helper.rb
module ListingsHelper

   def style_listings(listing)   
      amenities = Amenity.where("listing_id = ?", "#{listing.id}")
      string_array = ""
      amenities.each do |amenity|
         string_array = string_array + amenity.amenity.to_s + ", "
      end
   # NOTE: LISTING.IMAGE IS AN ARRAY!!! YOU ARE ONLY DISPLAYING THE FIRST PICTURE
   styled_listing = """
   <div class='row align-items-center justify-content-center' style='margin-top: 5%; margin-bottom: 5%;'>
   <div class='col-sm-12'>
   <div class='card'>      
   <img class='card-img-top listing-pic-on-profile-pg' src='#{listing.image}' style='' />      
   <div class='row card-body'>
   <div class='row col-sm-12'>
   <h3> #{listing.title} </h3>
   </div>
   <div class='col-md-6'>
   <div class='row col-sm-12'>
   <div>  #{listing.property_scope} with a maximum of #{listing.number_of_guests} guests </div>
   <div class='row col-sm-12'>
   <div> Amenities available to guests: #{string_array} </div>   
   </div>
   </div>
   <p class='card-text'>#{listing.description} <br/> <a href='/listing/#{listing.id}'>View property</a></p>
   </div>
   <div class='col-md-6'>"""   

   return styled_listing
end

def render_booking_form
   styled_string = """<div class='form-group' style='margin-top: 2%;'> <div class='row'>

   <div class='col-md-6 form-group'>
   <label>Check In</label>
   <input type='date' class='form-control' id='inputCheckin' name='booking[start_date]'>
   </div>

   <div class='col-md-6 form-group'>
   <label>Check Out</label>
   <input type='date' class='form-control' id='inputCheckout' name='booking[end_date]'>
   </div>

   </div>
   </div>
   </div>
   </div>
   </div>

   </div>
   <hr>
   """
   return styled_string
end


def generate_amenities
   options = ["TV", "Hairdryer", "Towels", "Dishwasher", "Microwave"]
   buttons = []
   counter = 0

   options.each do |option|
      button = "<div class='form-group' style='margin-right: 2%'>
      <label> #{option} </label>
      <div class='radio'>
      <input type='radio' value=#{option} name='amenity[option#{counter}]'>
      </div>
      </div>"
      buttons.push(button)
      counter += 1
   end
   return buttons

end

def upload_files
   str = """<!-- Upload Files: Hidden by default -->
   <div id='upload-files-area' class='container' style='display: none;'>
   <div class='panel panel-default'>
   <a href='#' onclick='hideUploadArea()' class='close file-upload-close' aria-label='close'>&times;</a>
   <div class='panel-heading'><strong>Upload Files</strong></div>      
   <div class='panel-body'>

   <!-- Standar Form -->
   <h4>Select files from your computer</h4>
   """

   # <%= form_for listings, url: '/listing/#{listing.id}', :html => {:class => 'profile-row-item', :id=>'js-upload-form', :enctype=>'multipart/form-data'}, method: "post" do |f| %>
   #    <div class='form-inline'>
   #    <div class='form-group'>

   #    <%= f.file_field :image, :html => {:name => 'files[]', :id=>'js-upload-files', :multiple} %> 
   #    </div>
   #    <%= f.submit "Upload Images" :html => {:class='btn btn-sm btn-primary', :id='js-upload-submit'}%>

   #    </div>
   #    </div>
   #    <% end %>

   #    <form action='' method='post' enctype='multipart/form-data' id='js-upload-form'>
   #    <div class='form-inline'>
   #    <div class='form-group'>
   #    <input type='file' name='files[]' id='js-upload-files' multiple>
   #    </div>
   #    <button type='submit' class='btn btn-sm btn-primary' id='js-upload-submit'>Upload files</button>
   #    </div>
   #    </form>

      # """<!-- Drop Zone -->
      # <h4>Or drag and drop files below</h4>
      # <div class='upload-drop-zone' id='drop-zone'>
      # Just drag and drop files here
      # </div>

      # <!-- Progress Bar -->
      # <div class='progress'>
      # <div class='progress-bar' role='progressbar' aria-valuenow='60' aria-valuemin='0' aria-valuemax='100' style='width: 60%;'>
      # <span class='sr-only'>60 Complete</span>
      # </div>
      # </div>

      # <!-- Upload Finished -->
      # <div class='js-upload-finished'>
      # <h3>Processed files</h3>
      # <div class='list-group'>
      # <a href='#' class='list-group-item list-group-item-success'><span class='badge alert-success pull-right'>Success</span>image-01.jpg</a>
      # <a href='#' class='list-group-item list-group-item-success'><span class='badge alert-success pull-right'>Success</span>image-02.jpg</a>
      # </div>
      # </div>
      # </div>
      # </div>
      # </div> <!-- /container -->
      # <!-- End of File Upload -->"""
      return str
   end
end

app/views/listings/_create_booking.erb
<div class="login-form">
 <div class="container">   
  <div class="login-form login-booking">
   <div class="main-div">
    <div class="panel">

      <h2 style="color: #ff6969; font-size: 25px;"><strong>Price per night: <%= Listing.find(params[:id]).price_per_night %> </strong></h2>           

    </div>
    <%= form_for :booking, url: create_booking_path(params[:id]), id: "create-booking", class: "listings" do |form| %>

    <div class="form-group" style="margin-top: 2%;">

      <div class="row">

       <div class="col-md-6 form-group">
        <label>Check In</label>
        <input type="date" class="form-control" id="inputCheckin" name="booking[start_date]">
      </div>

      <div class="col-md-6 form-group">
        <label>Check Out</label>
        <input type="date" class="form-control" id="inputCheckout" name="booking[end_date]">
      </div>

    </div>

     <!--  <div class="form-group">
        <label for="selectGuests">Guests</label>
        <select class="form-control" id="selelctGuests" name="booking[num_guests]">
         <option>1</option>
         <option>2</option>
         <option>3</option>
         <option>4</option>
         <option>5</option>
      </select>          
    </div> -->

    <input type="hidden" value="<%=current_user.id%>" name="booking[user_id]">
    <input type="hidden" value="<%= params[:id]%>" name="booking[listing_id]">      
    <button type="submit" class="btn btn-primary">Book</button>

    <%end%>  
  </div>
</div>
</div>
</div>
</div>

app/views/listings/_listings_create.html.erb
<div class="login-form">
  <div class="container">   
    <div class="login-form">
      <div class="main-div">
        <div class="panel">

          <h2 style="color: #ff6969; font-size: 25px;"><strong>About your property</strong></h2>          

        </div>                

        <%= form_for :user, url: listings_create_path, id: "listings", class: "listings" do |form| %>

        <div class="row" style="margin-top: 2%;">

          <div class="col-sm-12 col-md-6 form-group">
            <label>Listing Title</label>
            <input style="text-align: center;" type="text" class="form-control" id="inputLocation" placeholder="Title" name="user[title]">
          </div>

          <div class="col-sm-12 col-md-6 form-group">
            <label>Describe briefly your property</label>
            <input style="text-align: center;" type="text" class="form-control" id="inputLocation" placeholder="Brief Description" name="user[description]">
          </div>

        </div>

        <div class="row" style="margin-top: 2%;">

          <div class="col-sm-12">
            <label>Address</label>
          </div>

          <div class="col-md-4 form-group">            
            <input style="text-align: center;" type="text" class="form-control" id="inputLocation" placeholder="Street" name="user[street]">
          </div>   

          <div class="col-md-4 form-group">            
            <input style="text-align: center;" type="text" class="form-control" id="inputLocation" placeholder="City" name="user[city]">
          </div>      

          <div class="col-md-4 form-group">            
            <input style="text-align: center;" type="text" class="form-control" id="inputLocation" placeholder="Country" name="user[country]">
          </div>   
        </div>   

        <div class="row" style="margin-top: 2%;">

          <div class="col-md-4 form-group">
            <label for="property-type">Property type</label>          
            <select class="form-control" id="property-type" name="user[property_type]">
              <option>Appartment</option>
              <option>House</option>
              <option>Unique Space</option>            
              <option>Bed and Breakfast</option>            
              <option>Hotel Room</option>            
            </select>
          </div>

          <div class="col-md-4 form-group">
            <label for="property-scope">Available to guests</label>
            <select class="form-control" id="property-scope" name="user[property_scope]">
              <option>Entire place</option>
              <option>Private room</option>
              <option>Shared room</option>            
            </select>
          </div>

          <div class="col-md-4 form-group">
            <label>Price per night</label>
            <input type="text" class="form-control" id="inputLocation" placeholder="$$$" name="user[price_per_night]">
          </div>   

          <div class="col-md-4 form-group">
            <label for="sel-guests">Max no. of guests</label>
            <select class="form-control" id="sel-guests" name="user[number_of_guests]">
              <option>1</option>
              <option>2</option>
              <option>3</option>
              <option>5</option>
              <option>6</option>
              <option>7</option>
              <option>8</option>
            </select>  

          </div>        

          <!-- Amenities -->
          <div class="form-group col-md-8" style="display: inline-block;">       
            <div class="row justify-content-center" style="margin-top: 2%;">

              <div class="col-sm-12">
                <label>What amenities are available to guests:</label>
              </div>

              <% @tags = generate_amenities %>
              <% @tags.each do |tag| %>
              <%= raw tag %>
              <% end %>

            </div>
          </div>        

          <button type="submit" class="btn btn-primary">Create listing</button>

          <%end%>  
        </div>

      </div>
    </div>
  </div>

app/views/listings/_listings_search.html.erb
<div class="login-form">
  <div class="container">   
    <div class="login-form login-booking">
      <div class="main-div">
        <div class="panel">

          <h2 style="color: #ff6969; font-size: 25px;"><strong>Your ideal place</strong></h2>           

        </div>

        <%= form_for :user, url: listings_search_path, id: "listings", class: "listings" do |form| %>

        <div class="form-group" style="margin-top: 2%;">
          <label>Where?</label>
          <input style="text-align: center" type="text" class="form-control" id="inputLocation" placeholder="Anywhere" name="user[location]">
        </div>

        <!-- <div class="row">

          <div class="col-md-6 form-group">
            <label>Check In</label>
            <input type="date" class="form-control" id="inputCheckin" name="user[check_in]">
          </div>

          <div class="col-md-6 form-group">
            <label>Check Out</label>
            <input type="date" class="form-control" id="inputCheckout" name="user[check_out]">
          </div>

        </div>
        
        <div class="form-group">
          <label for="selectGuests">Guests</label>
          <select class="form-control" id="selelctGuests" name="user[guests]">
            <option>1</option>
            <option>2</option>
            <option>3</option>
            <option>4</option>
            <option>5</option>
          </select>          
        </div> -->

        <button type="submit" class="btn btn-primary">Search</button>

        <%end%>  
      </div>

    </div>
  </div>
</div>

app/views/listings/create.html.erb
<!-- Listings create form -->
<%= render partial: 'listings/listings_create' %>

<script>

// My custom carousel function
let counter = 2
let started = true
window.setInterval(function(){

// Reset counter
if (counter === 4){
  counter = 1
  started = false
}
// Add active class
if(counter !== 0){
  let nextItem = document.getElementById('carousel' + String(counter))    
  nextItem.classList.add("active")  
} else{
  let nextItem = document.getElementById('carousel1')
  nextItem.classList.add("active")  
}

// Remove active class
if (counter === 1 && started === false){
  let prevItem = document.getElementById('carousel3')
  prevItem.classList.remove("active") 
} else if (counter === 2){
  let prevItem = document.getElementById('carousel1')
  prevItem.classList.remove("active") 
} else if(counter === 3){
  let prevItem = document.getElementById('carousel2')
  prevItem.classList.remove("active") 
}

counter += 1

}, 7000);



</script>

app/views/listings/listing.html.erb
<div>
 <%=image_tag(Listing.find(params[:id]).image, :class => "container-fluid listing-profile-img ")%>
</div>

<div class="container">
 <div class="row" style="margin-top: 3%; margin-bottom: 3%;">
  <div class="col-sm-12 col-md-6">
   <div class="container" style="margin: auto; padding-top: 5%;">
    <h3> <%= @listing.title %> </h3>
    <div> <%= @listing.property_scope %> with a maximum of <%= @listing.number_of_guests %> guests </div>
    
    <div> Amenities available to guest:  </div>
    <% @amenities.each do |amenity| %>
    <%= amenity.amenity %>
    <% end %>    
    
    <p><%= Listing.find(params[:id]).description%></p>

  </div>
</div>

<div class="col-sm-12 col-md-6">
 <div class="login-form">
  <div class="container">   
    <div class="login-form profile-booking">
     <div class="main-div">
      <div class="panel">

        <h2 style="color: #ff6969; font-size: 25px;"><strong>Price per night: <%= Listing.find(params[:id]).price_per_night %> </strong></h2>           

      </div>
      <!-- create_booking_path(params[:id]) -->
      <%= form_for :booking, url: braintree_new_path(params[:id]), id: "create-booking", class: "listings" do |form| %>

      <div class="form-group" style="margin-top: 2%;">

        <div class="row">

         <div class="col-md-6 form-group">
          <label>Check In</label>
          <input type="date" class="form-control" id="inputCheckin" name="booking[start_date]">
        </div>

        <div class="col-md-6 form-group">
          <label>Check Out</label>
          <input type="date" class="form-control" id="inputCheckout" name="booking[end_date]">
        </div>

      </div>

      <div class="form-group">
        <label for="selectGuests">Guests</label>
        <select class="form-control" id="selelctGuests" name="booking[num_guests]">
         <option>1</option>
         <option>2</option>
         <option>3</option>
         <option>4</option>
         <option>5</option>
         <option>6</option>
         <option>7</option>
         <option>8</option>
       </select>          
     </div>
     <input type="hidden" value="" name="booking[total_price]">
     <input type="hidden" value="<%=current_user.id%>" name="booking[user_id]">
     <input type="hidden" value="<%= params[:id]%>" name="booking[listing_id]">      
     <button type="submit" class="btn btn-primary">Book</button>

     <%end%>  
   </div>
 </div>
</div>
</div>
</div>
</div>

</div>
</div>

app/views/listings/search_box.html.erb
<!-- Listings Search Form -->
<div>

   <%= render partial: 'listings/listings_search/' %>

</div>

<script>

// My custom carousel function
let counter = 2
let started = true
window.setInterval(function(){

// Reset counter
if (counter === 4){
 counter = 1
 started = false
}
// Add active class
if(counter !== 0){
 let nextItem = document.getElementById('carousel' + String(counter))    
 nextItem.classList.add("active")  
} else{
 let nextItem = document.getElementById('carousel1')
 nextItem.classList.add("active")  
}

// Remove active class
if (counter === 1 && started === false){
 let prevItem = document.getElementById('carousel3')
 prevItem.classList.remove("active") 
} else if (counter === 2){
 let prevItem = document.getElementById('carousel1')
 prevItem.classList.remove("active") 
} else if(counter === 3){
 let prevItem = document.getElementById('carousel2')
 prevItem.classList.remove("active") 
}

counter += 1

}, 7000);



</script>

app/views/listings/show_search_results.html.erb
<div class="container listings-search-results">
   <div class="row" style="margin-top: 5%;">
      <% @listings.each do |listing| %>
      <div class='col-sm-12 col-md-4 align-items-center justify-content-center' >
         <div class='col-sm-12'>
            <div class='card'>      
               <img class='card-img-top listing-pic-on-profile-pg img-thumbnail' src='<%=listing.image%>' style='width: 100%; height: 100%;' />      
               <div class='row card-body'>
                  <div class='col-md-12'>
                     <p class='card-text'><%=truncate(listing.description, :length => 200) %> <br/> <a href='/listing/<%=listing.id%>'>View property</a></p>
                  </div>                  
               </div>
            </div>
         </div>
      </div>
      <% end %>
   </div>
   <%= will_paginate @listings, renderer: BootstrapPagination::Rails %>
</div>