config/routes.rb
Rails.application.routes.draw do

  # scope as "amenities_create" do
  #   post "/amenities/create/amenity" => "amenities#create"
  # end


  post '/update/user/description' => 'users#update_description'

  scope as: "listings_delete" do  
    post "/listings/delete/:id" => "listings#delete"
  end

  scope as: "braintree_new" do
    get '/braintree/new/:id' => 'braintree#new'
    post '/braintree/new/:id' => 'braintree#new'
  end
  
  scope as: "braintree_checkout" do
    post '/braintree/checkout/:id' => "braintree#checkout"
    get '/braintree/checkout/:id' => "braintree#checkout"
  end

  root 'sessions#login'

  get "/auth/:provider/callback" => "sessions#create_from_omniauth"    

  get "/users_edit" => "users#show"
  post "/users_edit" => "users#edit"

  get "/listings_search_box" => "listings#search_box"
  post "/listings_search_box" => "listings#search_box"
  get "/listings_search" => "listing#search"
  post "/listings_search" => "listings#search_results" 

  post "/host_property" => "listings#create"
  get "/host_property" => "listings#create"
  get "/listings_create" => "listings#create"
  post "listings_create" => "listings#create_new_listing"  

  scope as: "listing" do
    get "/listing/:id" => "listings#show"    
  end

  post "/listing/:id" => "listings#update"

  scope as: "user_profile" do
    post "/user_profile/:id" => "users#profile"
    get "/user_profile/:id" => "users#profile"
  end

  scope as: "create_booking" do
    post "/create_booking/:id" => "bookings#create"
    get "/create_booking/:id" => "bookings#create"
  end

  delete "/log_out" => "sessions#destroy", as: :custom_sign_out
  get "/sign_in" => "sessions#sign_in", as: :custom_sign_in 


  resources :users, only: [:create, :edit, :update] do
    resource :password,
    controller: "clearance/passwords",
    only: [:create, :edit, :update]
  end
  
  post "/session" => "sessions#create"


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User  


  mount_uploader :avatar, AvatarUploader  

  #access privilages 
  enum role: {member:0, host:1, admin:2}

  #Db
  has_many :authentications, dependent: :destroy
  has_many :listings, dependent: :destroy
  has_many :bookings, dependent: :destroy
  
  #Validation  
  validates :first_name, presence: true
  validates :last_name, presence: true 
  validates :email, presence: true, uniqueness: true  
  
  def self.create_with_auth_and_hash(authentication, auth_hash)

   user = self.create!(
    first_name: auth_hash["info"]["first_name"],
    last_name: auth_hash["info"]["last_name"],
    email:auth_hash["info"]["email"],
    password: SecureRandom.hex(10),
    birthdate: nil,
    remote_avatar_url: auth_hash["info"]["image"],
    role: 0,   
    )   

   user.authentications << authentication
   return user
 end

 # grab google to access google for user data
 def google_token
   x = self.authentications.find_by(provider: 'google_oauth2')
   return x.token unless x.nil?
 end

 

end

app/controllers/users_controller.rb
include ListingsHelper
class UsersController < Clearance::UsersController
   before_action :require_login, except: :create
   
   def create      

      @user = User.new(user_params)
      @user.role = 0
      
      if @user.save
         sign_in(@user)            
         redirect_to user_profile_path(@user.id)
      else
         #specify there something to trigger JS 
         #which will then open the registration box rather than login box         
         redirect_to sign_in_path
      end
   end

   def show
   end

   def update_description
      current_user.description = params[:user][:description]
      current_user.save       
      redirect_to user_profile_path(current_user.id)
   end

   def edit      
      # current_user.update(:birthdate => params[:user][:birthdate], :password params[:user][:password])
   end

   def update
      current_user.update(avatar: params[:user][:avatar])     
      redirect_to user_profile_path(current_user.id)
   end

   def profile      
      #Display user info
      @user_name = User.find(params[:id]).first_name + " " + User.find(params[:id]).last_name
      @user_first_name = User.find(params[:id]).first_name
      @description = current_user.description

      if @description == nil or @description == ""
         @description = "Tell a story about yourself ..."
      end      
      

      #Display property hosted by the user
      user_listings = Listing.where("user_id = ?", "#{params[:id]}")
      if  !user_listings[0].nil?
         @has_listings = true
         listing = Listing.where("user_id = ?", "#{current_user.id}")
         @listings = listing         
      else
         @has_listings = false
      end

      @booking_form = render_booking_form
      
   end

   private

   def user_params    
     # user_params ||= params.require(:user).permit(:email, :first_name, :last_name, :birthdate, :password, :avatar, :role, :description)
     params.require(:user).permit(:email, :first_name, :last_name, :birthdate, :password, :avatar, :role, :description)
  end   
end

app/views/users/_edit_user.html.erb
<div class="login-form">
   <div class="container">   
      <div class="login-form">
         <div class="main-div">
            <div class="panel">

               <%= form_for :session, url: users_edit_path, id: "edit-user", class: "edit-user-info" do |form| %>

               <div class="form-group email-signup">
                  <label>Date of Birth</label>
                  <input type="date" class="form-control" id="inputBirthdate" placeholder="Date of Birth" name="user[birthdate]">
               </div>

               <div class="form-group">
                  <label>Password</label>
                  <input type="password" class="form-control" id="inputPassword" placeholder="Password" name="user[password]">
               </div>

               <button type="submit" class="btn btn-primary">Continue</button>          

               <% end %>
            </div>
         </div>
      </div>
   </div>
</div>

app/views/users/_register.html.erb
<%= form_for :user, url: users_path, id: "clearance", class: "" do |form| %>

<div class="form-group email-signup">
  <input type="email" class="form-control" placeholder="Email Address" name="user[email]"  style="text-align: center">
</div>

<div class="form-group">
  <input type="text" class="form-control" placeholder="First Name" name="user[first_name]"  style="text-align: center">
</div>

<div class="form-group">
   <input type="text" class="form-control" placeholder="Family Name" name="user[last_name]"  style="text-align: center">
</div>

<div class="form-group">
   <input type="date" class="form-control" placeholder="Date of birth" name="user[birthdate]"  style="text-align: center">
</div>

<div class="form-group">
   <input type="password" class="form-control" placeholder="Password" name="user[password]"  style="text-align: center">
</div>

<button type="submit" class="btn btn-primary">Register</button>

<%end%>  

app/views/users/profile.html.erb
<div class="container">

 <div class="row">
  <div class="col-sm-12" >
   <%=image_tag(User.find(params[:id]).avatar, :class => "profile-row-item profile-pic")%>   
   
   <% if current_user.id == params[:id].to_i %>
   <%= form_for current_user, url: "/users/#{current_user.id}", :class => "profile-row-item", method: "patch" do |f| %>

   <div class="profile-row-item">
     <%= f.file_field :avatar  %> 

     <%= f.submit "Edit Avatar" %>
   </div>
   <% end %>
   <% end %>

 </div>

 <div class="col-sm-12 " style="margin-top: 1%;">
  <div class="card">
   <div class="card-header">
     <%= @user_name %>
   </div>
   <div class="card-body">
    <h5 class="card-title">About <%= @user_first_name %></h5>
    <p id="user-description-current" class="card-text"><%= @description %></p>         
    
    <% if current_user.id == params[:id].to_i %>             

    <div id="user-description-text-box">

      <%= form_for :update_usr_description, url: update_user_description_path, id: "usr-description-form", class: "" do |form| %>
      
      <input type="text" class="form-control" placeholder="Describe yourself" name="user[description]" style="text-align: center">  
      
      <button type="submit" class="btn btn-success" style="margin-top: 1%;">Save changes</button> 
      <%end%>

    </div>
    <a style="margin-top: 1%;" href="#" id="update-user-description-btn" class="btn btn-primary" onclick="event.preventDefault();updateUserDescription()">Update Description</a>    
    <% end %>
  </div>
</div>
</div>
</div>


<!-- Display listings -->
<% if @has_listings %>

<div class="container">

  <div class="row" style="text-align: center;">

    <div class="col-sm-12" style="text-align:center; margin-top: 10%;">         
     <h2 > Hosted property </h2>
     <hr>
   </div>

   <div class="container listings-search-results">

    <% @listings.each do |listing| %>    
    
    <%= style_listings(listing).html_safe %>   

    <!-- Render booking form -->

    <div class="login-form">
     <div class="container">   
      <div class="login-form profile-booking">
       <div class="main-div">
        <div class="panel">

          <h2 style="color: #ff6969; font-size: 25px;"><strong>Price per night: <%= listing.price_per_night %> </strong></h2>           

        </div>
        <%= form_for :booking, url: braintree_new_path(params[:id]), id: "create-booking", class: "listings" do |form| %>

        <div class="form-group" style="margin-top: 2%;">

          <div class="row">

           <div class="col-md-6 form-group">
            <label>Check In</label>
            <input type="date" class="form-control" id="inputCheckin" name="booking[start_date]">
          </div>

          <div class="col-md-6 form-group">
            <label>Check Out</label>
            <input type="date" class="form-control" id="inputCheckout" name="booking[end_date]">
          </div>

        </div>

        <div class="form-group">
          <label for="selectGuests">Guests</label>
          <select class="form-control" id="selelctGuests" name="booking[num_guests]">
           <option>1</option>
           <option>2</option>
           <option>3</option>
           <option>4</option>
           <option>5</option>
           <option>6</option>
           <option>7</option>
           <option>8</option>
         </select>          
       </div>

       <input type="hidden" value="<%=current_user.id%>" name="booking[user_id]">
       <input type="hidden" value="<%= listing.id%>" name="booking[listing_id]">      
       <button type="submit" class="btn btn-primary">Book</button>

       <%end%>  
     </div>
   </div>
 </div>
</div>
</div>
<!-- End of booking form -->
</div>

<% if current_user.id = params[:id] %>
<div class="row col-sm-12" style="margin-top: 2%;">

  <div class="form-group col-sm-12 col-md-6">
    <%= button_to 'Delete Listing', listings_delete_path(id: listing.id), method: :post, :class => 'btn btn-danger' %>
  </div>

  <!-- Upload multiple files -->
  <!-- <a class="btn btn-soial-icon btn-facebook" onclick="showUploadArea()"><i class="fa fa-upload"></i></a>
    <div class="form-group col-sm-12 col-md-6"> -->

      <!-- Upload Files: Hidden by default -->
    <!-- <div id='upload-files-area' class='container' style='display: none;'>
     <div class='panel panel-default'> -->
       <!-- <a href='#' onclick='hideUploadArea()' class='close file-upload-close' aria-label='close'>&times;</a> -->
       <!-- <div class='panel-heading'><strong>Upload Files</strong></div>      
       <div class='panel-body'>
       -->
       <!-- Form -->
       <!-- <h4>Select files from your computer</h4> -->
       <%= form_for listing, url: "/listing/#{listing.id}", :html => {:class => 'profile-row-item', :id=>'js-upload-form', :enctype=>'multipart/form-data'}, method: "post" do |f| %>
         <!-- <div class='form-inline'>
          <div class='form-group'> -->

            <%= f.file_field :image, :html => {:name => 'files[]', :id=>'js-upload-files'} %> 
            <%= f.submit "Upload Images", :html => {:class=>'btn btn-sm btn-primary', :id=>'js-upload-submit'}%>
          </div>

      <!--   </div>
      </div> -->

      <!-- Drop Zone -->
      <!-- <h4>Or drag and drop files below</h4>
      <div class='upload-drop-zone' id='drop-zone'>
        Just drag and drop files here
      </div> -->

      <!-- Progress Bar -->
      <!-- <div class='progress'>
        <div class='progress-bar' role='progressbar' aria-valuenow='60' aria-valuemin='0' aria-valuemax='100' style='width: 60%;'>
          <span class='sr-only'>60 Complete</span>
        </div>
      </div> -->

      <!-- Upload Finished -->
      <!-- <div class='js-upload-finished'>
        <h3>Processed files</h3>
        <div class='list-group'>
          <a href='#' class='list-group-item list-group-item-success'><span class='badge alert-success pull-right'>Success</span>image-01.jpg</a>
          <a href='#' class='list-group-item list-group-item-success'><span class='badge alert-success pull-right'>Success</span>image-02.jpg</a>
        </div>
      </div>
    </div>
  </div>
</div> --> <!-- /container -->
<!-- End of File Upload -->

</div>
</div>
</div>
<% end %>




  <!-- div class="form-group col-sm-12 col-md-6">
    <%#= form_for listing, url: "/listing/#{listing.id}", :class => "profile-row-item", method: "post" do |f| %>


    <%#= f.file_field :image %> 

    <%#= f.submit "edit" %>
  </div>
</div>
<% end %> -->
</div>
<% end %>
</div>
<% end %>
</div>
</div>


</div>   





</div>

app/views/users/show.html.erb
<!-- Edit password and  date of birth -->
<div id="edit-user-info" class="edit-user-infp">

   <%= render partial: '/users/edit_user' %>

</div>