config/routes.rb
Rails.application.routes.draw do

  # scope as "amenities_create" do
  #   post "/amenities/create/amenity" => "amenities#create"
  # end


  post '/update/user/description' => 'users#update_description'

  scope as: "listings_delete" do  
    post "/listings/delete/:id" => "listings#delete"
  end

  scope as: "braintree_new" do
    get '/braintree/new/:id' => 'braintree#new'
    post '/braintree/new/:id' => 'braintree#new'
  end
  
  scope as: "braintree_checkout" do
    post '/braintree/checkout/:id' => "braintree#checkout"
    get '/braintree/checkout/:id' => "braintree#checkout"
  end

  root 'sessions#login'

  get "/auth/:provider/callback" => "sessions#create_from_omniauth"    

  get "/users_edit" => "users#show"
  post "/users_edit" => "users#edit"

  get "/listings_search_box" => "listings#search_box"
  post "/listings_search_box" => "listings#search_box"
  get "/listings_search" => "listing#search"
  post "/listings_search" => "listings#search_results" 

  post "/host_property" => "listings#create"
  get "/host_property" => "listings#create"
  get "/listings_create" => "listings#create"
  post "listings_create" => "listings#create_new_listing"  

  scope as: "listing" do
    get "/listing/:id" => "listings#show"    
  end

  post "/listing/:id" => "listings#update"

  scope as: "user_profile" do
    post "/user_profile/:id" => "users#profile"
    get "/user_profile/:id" => "users#profile"
  end

  scope as: "create_booking" do
    post "/create_booking/:id" => "bookings#create"
    get "/create_booking/:id" => "bookings#create"
  end

  delete "/log_out" => "sessions#destroy", as: :custom_sign_out
  get "/sign_in" => "sessions#sign_in", as: :custom_sign_in 


  resources :users, only: [:create, :edit, :update] do
    resource :password,
    controller: "clearance/passwords",
    only: [:create, :edit, :update]
  end
  
  post "/session" => "sessions#create"


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Airbnb</title>
  <%= csrf_meta_tags %>

  <%= favicon_link_tag 'logo.png' %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_link_tag    'listings', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_link_tag    'braintree', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'braintree', 'data-turbolinks-track': 'reload' %>
  
</head>

<body>

  <nav class="navbar navbar-expand-lg navbar-light bg-light navbar-fixed-top">    

    <%= link_to image_tag('logo.png', :class => "navbar-img ml-3"), "/listings_search_box" %> 

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <% if signed_in? %> 
    
    <%= form_for :user, url: listings_search_path, id: "listings", :html => {:class => "form-inline my-2 my-lg-0 ml-3"} do |form| %>   
    
    <input class="form-control mr-sm-2" type="search" placeholder="Your ideal place ..." aria-label="Search" name="user[location]">
    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>

    <% end %>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">

      <ul class="navbar-nav ml-auto">

        <li class="nav-item mr-3">
          <%= button_to 'Book place', listings_search_box_path, method: :post, :class => 'btn btn-light btn-outline-success' %>
        </li>            

        <li class="nav-item mr-3">
          <%= button_to 'Host property', host_property_path, method: :post, :class => 'btn btn-light' %>
        </li>      

        <li class="nav-item mr-3">
          <%= button_to 'Profile', user_profile_path(current_user.id), method: :post, :class => 'btn btn-light'%>           
        </li>    

        <li class="nav-item">
          <%= button_to 'Sign out', custom_sign_out_path, method: :delete, :class => 'btn btn-light'%>    
          <%end%> 
        </li>     
      </ul>

    </div>
  </nav>

  <% flash.each do |key, value| %>
  <div class="<%= flash_class(key) %>">
    <%= value %>
  </div>  
  <% end %>
  <% flash.clear %>

  <!-- Background pictures -->
  <% if @display_carousel %>
  <div class="carousel slide carousel-fade" data-ride="carousel">

    <!-- Wrapper for slides -->
    <div id="div-wrapper" class="carousel-inner" role="listbox">
      <div id="carousel1" class="item active">                  
      </div>
      <div id="carousel2" class="item">
      </div>
      <div id="carousel3" class="item">
      </div>
    </div>
  </div>
  <% else %>

  <div class="background-image"></div>

  <% end %>

  <%= yield %>

  <script type="text/javascript">
    $(document).ready(function () {
      $('.carousel').carousel({
        interval: 3000
      });

      $('.carousel').carousel('cycle');
    });
  </script>

</body>
</html>